In [296]:
import numpy as np
from tmu.models.autoencoder.autoencoder import TMAutoEncoder

In [297]:
def hamming_loss(pred, X_test):
    """
    Computes the Hamming loss between predicted and ground truth binary arrays.

    Parameters:
    - pred (numpy array): Binary predictions of shape (n_samples, n_bits).
    - X_test (numpy array): Ground truth binary values of shape (n_samples, n_bits).

    Returns:
    - float: Hamming loss (fraction of incorrect bits).
    """
    assert pred.shape == X_test.shape, "Shapes of pred and X_test must match"

    # Compute the number of differing bits
    incorrect_bits = np.sum(pred != X_test)

    # Total number of bits
    total_bits = np.prod(X_test.shape)

    # Hamming loss is the fraction of incorrect bits
    return incorrect_bits / total_bits

In [298]:
def test(tm, X):
    pred = tm.predict(X)

    print(pred)

    loss = [hamming_loss(X[i], pred[i]) for i in range(len(X))]

    return np.mean(loss), np.median(loss), np.max(loss), np.min(loss)

In [299]:
def simulate_data(n_samples):
    # First column: isWind
    # Second column: two bit integer temperature
    # Third column: two bit integer output power

    # Generate random values for each column.
    # There must be wind and temperature for output power. Higher temperature means higher output power.

    for i in range(n_samples):
        isWind = np.random.randint(0, 2)
        temperature = np.random.randint(0, 4) if isWind else 0
        outputPower = np.random.randint(0, 4) if isWind else 0

        yield [isWind, temperature, outputPower]

In [300]:
## Example columns: IsWind, Temperature, IsOutputPower,
X_train = np.array([
    [0, 0, 0, 0, 0],
    [1, 1, 1, 1, 1],
    [1, 1, 0, 1, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 1, 0, 0],
    [1, 0, 1, 0, 1],
    [1, 0, 1, 0, 1],
])

X_test = np.array([
    [0, 0, 0, 0, 0],
    [1, 1, 1, 1, 1],
    [1, 0, 1, 0, 1],
])

In [301]:
number_of_features = X_train.shape[1]
output_active = np.arange(number_of_features, dtype=np.uint32)

tm = TMAutoEncoder(
    number_of_clauses=500,
    T=500,
    s=15.0,
    output_active=output_active,
    max_included_literals=10,
    accumulation=1,
    feature_negation=True,
    platform="CPU",
    output_balancing=0,
)

print("Starting training for 15 epochs")

Starting training for 15 epochs


In [302]:
print(f"Starting training")

for e in range(15):
    tm.fit(X_train, number_of_examples=1)

    lmean, lmed, lmax, lmin = test(tm, X_test)
    # print(f"Epoch: {e + 1} Mean loss: {lmean:4f}, Median loss: {lmed:4f}, Max loss: {lmax:4f}, Min loss: {lmin:4f}")

Starting training
[[0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [1 1 1 1 1]
 [1 0 0 0 0]]
[[0 0 0 0 0]
 [1 1 1 1 1]
 [1 0 1 0 0]]
[[0 0 0 0 0]
 [1 1 1 1 1]
 [1 0 1 0 0]]
[[0 0 0 0 0]
 [1 1 1 1 1]
 [1 0 1 0 0]]
[[0 0 0 0 0]
 [1 1 1 1 1]
 [1 0 0 0 0]]
[[0 0 0 0 0]
 [1 1 1 1 1]
 [1 0 0 0 0]]
[[0 0 0 0 0]
 [1 1 1 1 1]
 [1 0 0 0 0]]
[[0 0 0 0 0]
 [1 1 1 1 1]
 [1 0 0 0 0]]
[[0 0 0 0 0]
 [1 1 1 1 1]
 [1 0 1 0 1]]
[[0 0 0 0 0]
 [1 1 1 1 1]
 [1 0 1 0 0]]
[[0 0 0 0 0]
 [1 1 1 1 1]
 [1 0 1 0 1]]
[[0 0 0 0 0]
 [1 1 1 1 1]
 [1 0 1 0 1]]
[[0 0 0 0 0]
 [1 1 1 1 1]
 [1 0 1 0 1]]
